FORMAT: 1A

# Introduction
Aplicação de gerenciamento em clínica odontologica.

## Architecture
+

## Integrations
+ OAUTH2 - Autenticação por meio de token de acesso, definindo escopos, o quais serviram para definição de qual cliente esta conectado ao serviço.
